apiVersion: v1
kind: Namespace
metadata:
  name: dev2
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
  namespace: dev2
spec:
  limits:
    - default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "300m"
        memory: "256Mi"
      type: Container
