apiVersion: v1
kind: Service
metadata:
  name: name-spceapp1-nginx-service
  labels:
    app: nginx-namespace-app1
  namespace: dev2
spec:
  type: LoadBalancer
  selector:
    app: nginx-namespace-app1
  ports:
    - port: 80
      targetPort: 80