apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-namespace-deploy1
  labels:
    app: nginx-namespace-app1
  namespace: dev2
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: nginx-namespace-app1
  template:
    metadata:
      labels:
        app: nginx-namespace-app1
    spec:
      containers:
        - name: nginx-namespace-app1
          image: stacksimplify/kube-nginxapp1:1.0.0
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"