apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backendrestapp

spec:
  #type
  selector:
    app: backendrestapp
  ports:
    - name: http
      port: 8080
      targetPort: 8080