apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployement
  labels:
    app: backend-restapp
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backendrestapp
    
  template:
    metadata:
      name: containerfor-backend
      labels:
        app: backendrestapp
    spec:
      - name: backendcontainer
        image: stacksimplify/kube-helloworld:1.0.0
        ports:
          - containerPort: 8080