apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium-retain-sc
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain    #default is delete. Retain is recomended
volumeBindingMode: WaitForFirstConsumer  #default is immediate 
allowVolumeExpansion: true
parameters:
  storageaccounttype: Premium_LRS  
  kind: managed   #default is shared
