apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-deploy1
  labels:
    app: nginx-ingress-app1
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: nginx-ingress-app1
  template:
    metadata:
      labels:
        app: nginx-ingress-app1
    spec:
      containers:
        - name: nginx-ingress-app1
          image: stacksimplify/kube-nginxapp1:1.0.0
          ports:
            - containerPort: 80