apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-clusterip1
  labels:
    app: nginx-ingress-app1
spec:
  type: ClusterIP
  selector:
    app: nginx-ingress-app1
  ports:
    - port: 80
      targetPort: 80 