apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-deploy2
  labels:
    app: nginx-ingress-app2
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: nginx-ingress-app2
  template:
    metadata:
      labels:
        app: nginx-ingress-app2
    spec:
      containers:
        - name: nginx-ingress-app2
          image: stacksimplify/kube-nginxapp2:1.0.0
          ports:
            - containerPort: 80