apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-clusterip2
  labels:
    app: nginx-ingress-app2
spec:
  type: ClusterIP
  selector:
    app: nginx-ingress-app2
  ports:
    - port: 80
      targetPort: 80 