apiVersion: v1
kind: Service
metadata: 
  name: azurefile-nginx-service
  labels:
    app: nginx-app
spec:
  type: LoadBalancer
  selector:
    app: nginx-app
  ports:
    - port: 80
      targetPort: 80